# Random Forest

In [36]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/students_performance_datasets.csv')

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   student_id                   300 non-null    int64
 1   gender                       300 non-null    str
 2   age                          300 non-null    int64
 3   race/ethnicity               300 non-null    str
 4   parental level of education  300 non-null    str
 5   lunch                        300 non-null    str
 6   test preparation course      300 non-null    str
 7   study_hours_per_day          300 non-null    float64
 8   attendance_percentage        300 non-null    float64
 9   math score                   300 non-null    int64
 10  reading score                300 non-null    int64
 11  writing score                300 non-null    int64
dtypes: float64(2), int64(5), str(5)
memory usage: 28.3 KB

In [38]:
df.head()

,student_id,gender,age,race/ethnicity,parental level of education,lunch,test preparation course,study_hours_per_day,attendance_percentage,math score,reading score,writing score
0,1,female,18,group B,bachelor's degree,free/reduced,completed,2.49,69.03,67,67,66
1,2,male,17,group C,some high school,standard,completed,7.77,73.54,71,98,69
2,3,male,20,group D,bachelor's degree,free/reduced,none,2.64,66.82,76,59,64
3,4,male,15,group A,some high school,standard,completed,5.20,86.78,63,78,85
4,5,male,18,group A,high school,free/reduced,completed,3.29,94.07,78,69,92

In [39]:
df.isnull().sum()

student_id                     0
gender                         0
age                            0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
study_hours_per_day            0
attendance_percentage          0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [40]:
# Encoding
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [41]:
def encoding(df):
    for col in df.columns:
        if df[col].dtype=='str':
            df[col]=encoder.fit_transform(df[col])
    return (df)

In [42]:
df=encoding(df)

In [43]:
df.head()

,student_id,gender,age,race/ethnicity,parental level of education,lunch,test preparation course,study_hours_per_day,attendance_percentage,math score,reading score,writing score
0,1,0,18,1,1,0,0,2.49,69.03,67,67,66
1,2,1,17,2,5,1,0,7.77,73.54,71,98,69
2,3,1,20,3,1,0,1,2.64,66.82,76,59,64
3,4,1,15,0,5,1,0,5.20,86.78,63,78,85
4,5,1,18,0,2,0,0,3.29,94.07,78,69,92

In [46]:
# Train
x=df.drop('math score',axis=1)

In [54]:
y=df['math score'].astype(int)

In [62]:
y

0      67
1      71
2      76
3      63
4      78
       ..
295    85
296    96
297    55
298    64
299    66
Name: math score, Length: 300, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [57]:
# Random Forest
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()

In [58]:
rfr.fit(x_train,y_train)

RandomForestRegressor()

In [59]:
y_pred=rfr.predict(x_test)

In [67]:
y_pred

array([83.99, 72.3 , 80.37, 80.83, 73.98, 58.61, 80.51, 82.16, 77.64,
       81.41, 60.46, 77.63, 71.4 , 71.87, 78.8 , 61.6 , 79.43, 77.34,
       77.13, 64.18, 64.19, 75.14, 78.42, 88.27, 65.07, 75.9 , 68.  ,
       84.3 , 83.25, 77.93, 79.93, 79.97, 76.85, 76.67, 78.09, 78.44,
       80.96, 73.37, 74.61, 74.21, 67.3 , 68.06, 69.48, 61.5 , 80.39,
       80.53, 61.8 , 75.23, 66.53, 78.04, 72.28, 71.07, 81.12, 85.84,
       74.89, 69.79, 77.11, 73.62, 79.09, 73.59])

In [68]:
# Evaluation 
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [69]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [70]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 9.285833333333334
mse: 124.16420833333335
r2: 0.10752419915183153

# Linear Regression

In [71]:
from sklearn.linear_model import LinearRegression

In [72]:
lr=LinearRegression()

In [73]:
lr.fit(x_train,y_train)

LinearRegression()

In [74]:
y_pred=lr.predict(x_test)

In [75]:
y_pred

array([82.79521678, 75.44345238, 78.47933708, 83.75455241, 78.1213228 ,
       60.57741949, 82.58776738, 86.24880363, 81.96874086, 80.89143788,
       69.22709672, 78.70091361, 72.41521074, 73.64299089, 82.40695694,
       65.83097378, 83.28775652, 84.28978959, 77.82016183, 72.46888147,
       64.82878323, 76.19965451, 74.4505661 , 85.73023428, 64.86677499,
       73.83282032, 69.16753878, 88.61106122, 85.01245714, 79.75109799,
       75.8540245 , 80.70933702, 74.74888853, 73.03719009, 70.25845892,
       72.77834213, 79.6342462 , 70.91002956, 72.65233698, 73.24598868,
       66.65092399, 66.82876031, 68.79206648, 62.80281374, 84.1271423 ,
       87.45232302, 60.02977394, 77.2926275 , 74.79397394, 83.30974328,
       72.19260919, 70.72251574, 80.37550846, 81.67387001, 76.19234411,
       75.28736442, 78.944794  , 70.91537215, 79.56532635, 73.56069635])

In [76]:
# Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [77]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [78]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 8.595920933652534
mse: 106.131738089066
r2: 0.2371391947979058

# Decision Tree

In [79]:
from sklearn.tree import DecisionTreeRegressor

In [80]:
dt=DecisionTreeRegressor()

In [81]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [82]:
y_pred=dt.predict(x_test)

In [83]:
y_pred

array([ 78.,  84., 100.,  80.,  80.,  46.,  95.,  70.,  71.,  78.,  57.,
        61.,  57.,  76.,  67.,  59., 100.,  70.,  78.,  62.,  61.,  79.,
        65.,  96.,  69.,  81.,  57.,  96.,  78.,  85., 100.,  78.,  81.,
        85.,  63.,  84.,  94.,  83.,  63.,  82.,  82.,  79.,  78.,  61.,
        70.,  70.,  61.,  63.,  82., 100.,  65.,  71.,  87.,  81.,  65.,
        65.,  81.,  67.,  78.,  66.])

In [84]:
# Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [85]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [86]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 11.716666666666667
mse: 198.98333333333332
r2: -0.43026571147902337

In [87]:
import joblib

In [88]:
from joblib import dump,load

In [89]:
dump(rfr,'student_performance.joblib')

['student_performance.joblib']

In [90]:
model=load('student_performance.joblib')

In [91]:
dump(lr,'student.joblib')

['student.joblib']

In [92]:
dump(dt,'student_per.joblib')

['student_per.joblib']

# Tabulate

In [93]:
from tabulate import tabulate

In [94]:
resurts=[
['Random Forest',9.285833333333334
, 124.16420833333335,0.10752419915183153],
['Linear Regression', 8.595920933652534 ,106.131738089066,0.2371391947979058],
['Decision Tree', 11.716666666666667, 198.98333333333332,-0.43026571147902337]

]
headers=['Algoritm','mean_absolute_error','mean_squared_error','r2_score']
table=tabulate(resurts,headers=headers,tablefmt='grid',floatfmt='.4F')
print(table)

+-------------------+-----------------------+----------------------+------------+
| Algoritm          |   mean_absolute_error |   mean_squared_error |   r2_score |
+===================+=======================+======================+============+
| Random Forest     |                9.2858 |             124.1642 |     0.1075 |
+-------------------+-----------------------+----------------------+------------+
| Linear Regression |                8.5959 |             106.1317 |     0.2371 |
+-------------------+-----------------------+----------------------+------------+
| Decision Tree     |               11.7167 |             198.9833 |    -0.4303 |
+-------------------+-----------------------+----------------------+------------+