# Project

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('/Users/sunnatabdurayimov/Documents/temp_1781170705670.1228127840.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           str
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    str
 6   player_name             str
 7   competition_id          str
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), str(4)
memory usage: 169.3 MB

In [7]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

# Data bilan tanishuv

In [8]:
# appearance_id--ko'rinish id
#game id--> o'yin id
#player-->o'yinchi id
.....
#goals-->gollar(target qiymat)
#minutes_played--> o'ynagan vaqti

SyntaxError: invalid syntax (3067299849.py, line 4)

In [9]:
df.isnull().sum()

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
player_name               6
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

# Data Preprocessing

In [10]:
# mode
df.fillna({'player_name':df['player_name'].mode()[0]},inplace=True)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706801,4547798_811779,4547798,811779,985,985,2025-04-10,Alejandro Garnacho,EL,0,0,0,0,83
1706802,4547798_820374,4547798,820374,985,985,2025-04-10,Kobbie Mainoo,EL,1,0,0,0,7
1706803,4547798_923831,4547798,923831,985,985,2025-04-10,Leny Yoro,EL,0,0,1,0,90
1706804,4547798_926952,4547798,926952,985,985,2025-04-10,Patrick Dorgu,EL,0,0,0,0,90
1706805,4547798_93720,4547798,93720,1041,1041,2025-04-10,Alexandre Lacazette,EL,0,0,0,0,39

In [13]:
df.drop('player_id',axis=1,inplace=True)

In [14]:
df.isnull().any()

appearance_id             False
game_id                   False
player_club_id            False
player_current_club_id    False
date                      False
player_name               False
competition_id            False
yellow_cards              False
red_cards                 False
goals                     False
assists                   False
minutes_played            False
dtype: bool

# Encoding

In [15]:
df.nunique()

appearance_id             1706806
game_id                     66840
player_club_id               1063
player_current_club_id        438
date                         3738
player_name                 25141
competition_id                 43
yellow_cards                    3
red_cards                       2
goals                           7
assists                         7
minutes_played                122
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
encoder=LabelEncoder()

In [19]:
def encodlash(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return (df)

In [20]:
df=encodlash(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int64
 1   game_id                 int64
 2   player_club_id          int64
 3   player_current_club_id  int64
 4   date                    int64
 5   player_name             int64
 6   competition_id          int64
 7   yellow_cards            int64
 8   red_cards               int64
 9   goals                   int64
 10  assists                 int64
 11  minutes_played          int64
dtypes: int64(12)
memory usage: 156.3 MB

In [ ]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,2673,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,20519,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,20949,13,0,0,0,0,45
3,55776,2234418,73333,1274,6646,1,23556,13,0,0,0,0,90
4,55777,2234421,122011,195,3008,1,15316,13,0,0,0,1,90

# Scaling

In [21]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [22]:
def scaling(df):
    num_col=df.select_dtypes(include=['int64']).columns.drop('goals')
    df[num_col]=scaler.fit_transform(df[num_col])
    return (df)

In [23]:
df=scaling(df)
df.head()

,appearance_id,game_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.007724,0.002140,0.000000,0.106325,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.032658,0.009377,0.080144,0.024469,0.000268,0.816189,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.032678,0.009658,0.056663,0.004225,0.000268,0.833294,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.032679,0.009660,0.011541,0.060261,0.000268,0.936993,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.032679,0.009662,0.001759,0.027279,0.000268,0.609228,0.309524,0.0,0.0,0,0.166667,0.605442

# Training

In [34]:
x=df.drop('goals',axis=1)
x

,appearance_id,game_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,assists,minutes_played
0,0.032631,0.008627,0.007724,0.002140,0.000000,0.106325,0.142857,0.0,0.0,0.000000,0.605442
1,0.032658,0.009377,0.080144,0.024469,0.000268,0.816189,0.309524,0.0,0.0,0.000000,0.605442
2,0.032678,0.009658,0.056663,0.004225,0.000268,0.833294,0.309524,0.0,0.0,0.000000,0.299320
3,0.032679,0.009660,0.011541,0.060261,0.000268,0.936993,0.309524,0.0,0.0,0.000000,0.605442
4,0.032679,0.009662,0.001759,0.027279,0.000268,0.609228,0.309524,0.0,0.0,0.166667,0.605442
...,...,...,...,...,...,...,...,...,...,...,...
1706801,0.999579,0.989370,0.008921,0.008939,1.000000,0.027128,0.285714,0.0,0.0,0.000000,0.557823
1706802,0.999579,0.989370,0.008921,0.008939,1.000000,0.516985,0.285714,0.5,0.0,0.000000,0.040816
1706803,0.999580,0.989370,0.008921,0.008939,1.000000,0.539061,0.285714,0.0,0.0,0.000000,0.605442
1706804,0.999581,0.989370,0.008921,0.008939,1.000000,0.747375,0.285714,0.0,0.0,0.000000,0.605442
1706805,0.999581,0.989370,0.009429,0.009447,1.000000,0.042999,0.285714,0.0,0.0,0.000000,0.258503

In [35]:
y=df['goals']
y

0          2
1          0
2          0
3          0
4          0
          ..
1706801    0
1706802    0
1706803    1
1706804    0
1706805    0
Name: goals, Length: 1706806, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [38]:
x_train.shape

(1365444, 11)

In [39]:
x_test.shape

(341362, 11)

# Algorithm selection(1-usul)

In [40]:
from sklearn.linear_model import LinearRegression,LogisticRegression
lr=LinearRegression()

In [41]:
lr.fit(x_train, y_train)

LinearRegression()

In [42]:
y_pred=lr.predict(x_test)

In [44]:
y_pred[0]

np.float64(0.06823120525145397)

In [45]:
# Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [47]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
rmse=pow(mse,(1/2))

In [48]:
print(mae)
print(mse)
print(r2)
print(rmse)

0.17408654021713976
0.10982692370032857
0.011159000361235627
0.3314014539804081

# Algorithm selection(2-usul)

In [49]:
from sklearn.linear_model import LinearRegression,LogisticRegression
log_reg=LogisticRegression()

In [50]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [51]:
y_pred=log_reg.predict(x_test)

In [53]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(341362,))

In [54]:
#Evaluation
from sklearn.metrics import classification_report,accuracy_score

In [56]:
c_report=classification_report(y_test,y_pred)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [57]:
print(c_report)

              precision    recall  f1-score   support

           0       0.91      1.00      0.95    311810
           1       0.00      0.00      0.00     26373
           2       0.00      0.00      0.00      2820
           3       0.00      0.00      0.00       328
           4       0.00      0.00      0.00        28
           5       0.00      0.00      0.00         3

    accuracy                           0.91    341362
   macro avg       0.15      0.17      0.16    341362
weighted avg       0.83      0.91      0.87    341362