In [145]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/bank-.csv')

# Data bilan tanishuv

In [146]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45209 non-null  str
 4   default    45208 non-null  str
 5   balance    45210 non-null  float64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45210 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45203 non-null  float64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  Target     45205 non-null  str
dtypes: float64(3), int64(4), str(10)
memory usage: 5.9 MB

In [147]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,58,management,married,tertiary,no,2143.0,yes,no,unknown,5,may,261.0,1,-1.0,0,unknown,no
1,44,technician,single,secondary,no,29.0,yes,no,unknown,5,may,151.0,1,-1.0,0,unknown,no
2,33,entrepreneur,married,secondary,no,2.0,yes,yes,unknown,5,may,76.0,1,-1.0,0,unknown,no
3,47,blue-collar,married,unknown,no,1506.0,yes,no,unknown,5,may,92.0,1,-1.0,0,unknown,no
4,33,unknown,single,unknown,no,1.0,no,no,unknown,5,may,198.0,1,-1.0,0,unknown,no

In [148]:
df.isnull().sum()

age          0
job          0
marital      0
education    2
default      3
balance      1
housing      0
loan         0
contact      0
day          0
month        0
duration     1
campaign     0
pdays        8
previous     0
poutcome     0
Target       6
dtype: int64

# Data Preprocessing

In [149]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df.fillna({col:df[col].mode()[0]},inplace=True)
            else:
                df.fillna({col:df[col].mean()},inplace=True)
    return (df)

In [150]:
df=toldir(df)
df.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
Target       False
dtype: bool

# encoding

In [151]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [152]:
df.nunique()

age            77
job            12
marital         3
education       4
default         2
balance      7169
housing         2
loan            2
contact         3
day            31
month          12
duration     1574
campaign       48
pdays         560
previous       41
poutcome        4
Target          2
dtype: int64

In [153]:
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=2:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return (df)

In [154]:
df=encodla(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          45211 non-null  int64
 1   job          45211 non-null  int64
 2   marital      45211 non-null  int64
 3   education    45211 non-null  int64
 4   balance      45211 non-null  float64
 5   contact      45211 non-null  int64
 6   day          45211 non-null  int64
 7   month        45211 non-null  int64
 8   duration     45211 non-null  float64
 9   campaign     45211 non-null  int64
 10  pdays        45211 non-null  float64
 11  previous     45211 non-null  int64
 12  poutcome     45211 non-null  int64
 13  default_no   45211 non-null  int64
 14  default_yes  45211 non-null  int64
 15  housing_no   45211 non-null  int64
 16  housing_yes  45211 non-null  int64
 17  loan_no      45211 non-null  int64
 18  loan_yes     45211 non-null  int64
 19  Target_no    45211 non-null  int64
 20  Target_yes   45211 non-null  int64
dtypes: float64(3), int64(18)
memory usage: 7.2 MB

In [155]:
df.head()

,age,job,marital,education,balance,contact,day,month,duration,campaign,...,previous,poutcome,default_no,default_yes,housing_no,housing_yes,loan_no,loan_yes,Target_no,Target_yes
0,58,4,1,2,2143.0,2,5,8,261.0,1,...,0,3,1,0,0,1,1,0,1,0
1,44,9,2,1,29.0,2,5,8,151.0,1,...,0,3,1,0,0,1,1,0,1,0
2,33,2,1,1,2.0,2,5,8,76.0,1,...,0,3,1,0,0,1,0,1,1,0
3,47,1,1,3,1506.0,2,5,8,92.0,1,...,0,3,1,0,0,1,1,0,1,0
4,33,11,2,3,1.0,2,5,8,198.0,1,...,0,3,1,0,1,0,1,0,1,0

# scaling

In [156]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [157]:
def scaling(df):
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('duration')
    df[num_col]=scaler.fit_transform(df[num_col])
    return (df)

In [158]:
scaling(df)
df.head(-5)

,age,job,marital,education,balance,contact,day,month,duration,campaign,...,previous,poutcome,default_no,default_yes,housing_no,housing_yes,loan_no,loan_yes,Target_no,Target_yes
0,0.519481,0.363636,0.5,0.666667,0.092259,1.0,0.133333,0.727273,261.0,0.000000,...,0.000000,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.337662,0.818182,1.0,0.333333,0.073067,1.0,0.133333,0.727273,151.0,0.000000,...,0.000000,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,0.194805,0.181818,0.5,0.333333,0.072822,1.0,0.133333,0.727273,76.0,0.000000,...,0.000000,1.000000,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
3,0.376623,0.090909,0.5,1.000000,0.086476,1.0,0.133333,0.727273,92.0,0.000000,...,0.000000,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
4,0.194805,1.000000,1.0,1.000000,0.072812,1.0,0.133333,0.727273,198.0,0.000000,...,0.000000,1.000000,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45201,0.454545,0.363636,0.5,0.666667,0.078096,0.0,0.533333,0.818182,226.0,0.000000,...,0.014545,0.666667,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
45202,0.207792,0.000000,1.0,0.333333,0.077860,0.0,0.533333,0.818182,224.0,0.000000,...,0.000000,1.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
45203,0.064935,0.727273,1.0,0.666667,0.073829,0.0,0.533333,0.818182,266.0,0.000000,...,0.000000,1.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
45204,0.714286,0.454545,0.5,0.333333,0.098678,0.0,0.533333,0.818182,300.0,0.000000,...,0.029091,0.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
45205,0.090909,0.818182,1.0,0.333333,0.077388,0.0,0.533333,0.818182,386.0,0.016129,...,0.000000,1.000000,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

# Train

In [159]:
x=df.drop('duration',axis=1)

In [160]:
x

,age,job,marital,education,balance,contact,day,month,campaign,pdays,previous,poutcome,default_no,default_yes,housing_no,housing_yes,loan_no,loan_yes,Target_no,Target_yes
0,0.519481,0.363636,0.5,0.666667,0.092259,1.0,0.133333,0.727273,0.000000,0.000000,0.000000,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.337662,0.818182,1.0,0.333333,0.073067,1.0,0.133333,0.727273,0.000000,0.000000,0.000000,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,0.194805,0.181818,0.5,0.333333,0.072822,1.0,0.133333,0.727273,0.000000,0.000000,0.000000,1.000000,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
3,0.376623,0.090909,0.5,1.000000,0.086476,1.0,0.133333,0.727273,0.000000,0.000000,0.000000,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
4,0.194805,1.000000,1.0,1.000000,0.072812,1.0,0.133333,0.727273,0.000000,0.000000,0.000000,1.000000,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,0.818182,0.5,0.666667,0.080293,0.0,0.533333,0.818182,0.032258,0.000000,0.000000,1.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
45207,0.688312,0.454545,0.0,0.000000,0.088501,0.0,0.533333,0.818182,0.016129,0.000000,0.000000,1.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
45208,0.701299,0.454545,0.5,0.333333,0.124689,0.0,0.533333,0.818182,0.064516,0.212156,0.010909,0.666667,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
45209,0.506494,0.090909,0.5,0.333333,0.078868,0.5,0.533333,0.818182,0.048387,0.000000,0.000000,1.000000,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
45210,0.246753,0.181818,0.5,0.333333,0.099777,0.0,0.533333,0.818182,0.016129,0.216743,0.040000,0.333333,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [161]:
y=df['duration']

In [162]:
from sklearn.model_selection import train_test_split

In [163]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [164]:
x_train.shape

(36168, 20)

# Linear Regression

In [165]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [166]:
lr.fit(x_train,y_train)

LinearRegression()

In [167]:
y_pred=lr.predict(x_test)

In [168]:
y_pred[0]

np.float64(251.92180484137296)

In [169]:
# Evaluation
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [170]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [171]:
print('r2= ',r2)
print('mae= ',mae)
print('mse= ',mse)
print('rmse= ',rmse)

r2=  0.16952708852354126
mae=  157.20772876037253
mse=  56150.40778477012
rmse=  236.96077267085815

# DecisionTreeRegressor

In [172]:
from sklearn.tree import DecisionTreeRegressor
dt_reg=DecisionTreeRegressor()

In [173]:
dt_reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [174]:
y_pred=dt_reg.predict(x_test)

In [175]:
y_pred

array([615., 252., 297., ...,  19., 224.,  54.], shape=(9043,))

In [176]:
# Evaluation
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [177]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [178]:
print('r2= ',r2)
print('mae= ',mae)
print('mse= ',mse)
print('rmse= ',rmse)

r2=  -0.5984972554967642
mae=  209.8151608979321
mse=  108078.50743669136
rmse=  328.7529580653098

In [179]:
df.head()

,age,job,marital,education,balance,contact,day,month,duration,campaign,...,previous,poutcome,default_no,default_yes,housing_no,housing_yes,loan_no,loan_yes,Target_no,Target_yes
0,0.519481,0.363636,0.5,0.666667,0.092259,1.0,0.133333,0.727273,261.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.337662,0.818182,1.0,0.333333,0.073067,1.0,0.133333,0.727273,151.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,0.194805,0.181818,0.5,0.333333,0.072822,1.0,0.133333,0.727273,76.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
3,0.376623,0.090909,0.5,1.000000,0.086476,1.0,0.133333,0.727273,92.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
4,0.194805,1.000000,1.0,1.000000,0.072812,1.0,0.133333,0.727273,198.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0