In [5]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/Chocolate_Sales.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Order_ID         200000 non-null  str
 1   Product          200000 non-null  str
 2   Country          200000 non-null  str
 3   Channel          200000 non-null  str
 4   Salesperson      200000 non-null  str
 5   Order_Date       199563 non-null  str
 6   Discount_Pct     199511 non-null  float64
 7   Price_per_Box    199543 non-null  float64
 8   Marketing_Spend  199539 non-null  float64
 9   Boxes_Shipped    200000 non-null  int64
 10  Amount           200000 non-null  str
dtypes: float64(3), int64(1), str(7)
memory usage: 16.8 MB

In [7]:
df.head()

     Order_ID            Product  ... Boxes_Shipped  Amount
0  ORD-069833   Truffle Gift Box  ...            71  912.31
1  ORD-090726       85% Dark Bar  ...            84  245.91
2  ORD-042159       70% Dark Bar  ...            35   583.7
3  ORD-197166  Hazelnut Milk Bar  ...            92  211.27
4  ORD-112162  Almond Crunch Bar  ...           214  549.69

[5 rows x 11 columns]

# Data Preprocessing

In [8]:
df.isnull().sum()

Order_ID             0
Product              0
Country              0
Channel              0
Salesperson          0
Order_Date         437
Discount_Pct       489
Price_per_Box      457
Marketing_Spend    461
Boxes_Shipped        0
Amount               0
dtype: int64

In [9]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df.fillna({col:df[col].mode()[0]},inplace=True)
            else:
                df.fillna({col:df[col].mean()},inplace=True)
    return (df)

In [10]:
df=toldir(df)
df.isnull().any()

Order_ID           False
Product            False
Country            False
Channel            False
Salesperson        False
Order_Date         False
Discount_Pct       False
Price_per_Box      False
Marketing_Spend    False
Boxes_Shipped      False
Amount             False
dtype: bool

In [11]:
df.nunique()

Order_ID           200000
Product                12
Country                 5
Channel                 3
Salesperson            25
Order_Date           2000
Discount_Pct         2518
Price_per_Box        1382
Marketing_Spend     27320
Boxes_Shipped        1521
Amount              85605
dtype: int64

In [12]:
# Encoding
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [13]:

def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            df[col]=encoder.fit_transform(df[col])
        
    return (df)

In [14]:
df=encodla(df)
df.head()

   Order_ID  Product  Country  ...  Marketing_Spend  Boxes_Shipped  Amount
0     69832       10        0  ...           202.03             71   81962
1     90725        1        0  ...            55.18             84   27569
2     42158        0        4  ...            60.65             35   60264
3    197165        4        2  ...            52.00             92   23671
4    112161        2        0  ...           187.44            214   57308

[5 rows x 11 columns]

In [15]:
# Scaling
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [16]:
scaler

MinMaxScaler()

In [17]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Product')
num_col

Index(['Order_ID', 'Country', 'Channel', 'Salesperson', 'Order_Date',
       'Discount_Pct', 'Price_per_Box', 'Marketing_Spend', 'Boxes_Shipped',
       'Amount'],
      dtype='str')

In [18]:
def scaling(df):
    for col in num_col:
        df[num_col]=scaler.fit_transform(df[num_col])
    return (df)

In [19]:
df=scaling(df)
df.head()

   Order_ID  Product  Country  ...  Marketing_Spend  Boxes_Shipped    Amount
0  0.349162       10      0.0  ...         0.249055       0.314139  0.957455
1  0.453627        1      0.0  ...         0.064087       0.316523  0.322053
2  0.210791        0      1.0  ...         0.070977       0.307537  0.703986
3  0.985830        4      0.5  ...         0.060081       0.317990  0.276517
4  0.560808        2      0.0  ...         0.230677       0.340363  0.669455

[5 rows x 11 columns]

In [20]:
#Train
x=df.drop('Product',axis=1)

In [21]:
y=df['Product']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()

In [25]:
log_reg.fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [26]:
y_pred=log_reg.predict(x_test)

In [27]:
y_pred

array([10,  0, 10, ...,  0,  0,  0], shape=(40000,))

In [28]:
# Evaluation
from sklearn.metrics import classification_report,accuracy_score

In [29]:
report=classification_report(y_test,y_pred)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [30]:
print(report)

              precision    recall  f1-score   support

           0       0.36      0.94      0.52     12690
           1       0.00      0.00      0.00      1585
           2       0.00      0.00      0.00      1819
           3       0.00      0.00      0.00      1280
           4       0.00      0.00      0.00      1090
           5       0.00      0.00      0.00      3190
           6       0.00      0.00      0.00      2183
           7       0.49      0.33      0.39      4334
           8       0.00      0.00      0.00      2580
           9       0.00      0.00      0.00      1218
          10       0.29      0.17      0.21      6592
          11       0.00      0.00      0.00      1439

    accuracy                           0.36     40000
   macro avg       0.09      0.12      0.09     40000
weighted avg       0.21      0.36      0.24     40000

# Linear Regression

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lr=LinearRegression()

In [33]:
lr.fit(x_train,y_train)

LinearRegression()

In [34]:
y_pred=lr.predict(x_test)

In [35]:
y_pred

array([6.11391911, 4.42112287, 5.79450851, ..., 3.67524024, 4.62745827,
       5.08178106], shape=(40000,))

In [36]:
# Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [37]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [38]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 3.5135392715020375
mse: 15.246330589834347
r2: 0.045961519290273256

# Decision Tree

In [39]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
dtc=DecisionTreeClassifier()

In [44]:
dtc

DecisionTreeClassifier()

In [45]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [46]:
y_pred=dtc.predict(x_test)

In [47]:
y_pred

array([10,  0,  0, ..., 10,  0,  0], shape=(40000,))

In [48]:
# Evaluation
from sklearn.metrics import classification_report,accuracy_score

In [49]:
report=classification_report(y_test,y_pred)

In [50]:
print(report)

              precision    recall  f1-score   support

           0       0.41      0.41      0.41     12690
           1       0.06      0.06      0.06      1585
           2       0.10      0.11      0.10      1819
           3       0.09      0.10      0.09      1280
           4       0.03      0.04      0.04      1090
           5       0.12      0.12      0.12      3190
           6       0.12      0.12      0.12      2183
           7       0.50      0.47      0.48      4334
           8       0.08      0.08      0.08      2580
           9       0.05      0.05      0.05      1218
          10       0.31      0.30      0.30      6592
          11       0.03      0.03      0.03      1439

    accuracy                           0.27     40000
   macro avg       0.16      0.16      0.16     40000
weighted avg       0.27      0.27      0.27     40000

# Decision Tree Regressor

In [57]:
from sklearn.tree import DecisionTreeRegressor

In [58]:
dtr=DecisionTreeRegressor()

In [59]:
dtr

DecisionTreeRegressor()

In [60]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [61]:
y_pred=dtr.predict(x_test)

In [62]:
y_pred

array([10.,  8.,  7., ...,  4.,  0.,  0.], shape=(40000,))

In [63]:
# Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [66]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [67]:

print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 3.99685
mse: 28.0012
r2: -0.7521738852928448

In [51]:
# pip install tabulate
# !pip install tabulate
# %pip install tabulate

# Tabulate

In [55]:
%pip install tabulate

Requirement already satisfied: tabulate in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.10.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [56]:
from tabulate import tabulate

In [69]:
results=[
['Logisric Regression',0.36,0.94,0.52,0.36],
['Decision Tree',0.41,0.41,0.41,0.27]

]
headers=['Algorithn','Precision','Recall','F1_score','Accuracy_score']
table=tabulate(results,headers=headers,tablefmt='grid')
print(table)

+---------------------+-------------+----------+------------+------------------+
| Algorithn           |   Precision |   Recall |   F1_score |   Accuracy_score |
+=====================+=============+==========+============+==================+
| Logisric Regression |        0.36 |     0.94 |       0.52 |             0.36 |
+---------------------+-------------+----------+------------+------------------+
| Decision Tree       |        0.41 |     0.41 |       0.41 |             0.27 |
+---------------------+-------------+----------+------------+------------------+

In [74]:
from tabulate import tabulate
results=[
['Linear Regression',3.513539271,15.24633058,0.04596151929],
['Decision Tree Regressor',3.99685,28.0012,-0.75217388529]
]
headers=['Algorithm','mae','mse','r2']
table=tabulate(results,headers=headers,tablefmt='grid',floatfmt='.3F')
print(table)

+-------------------------+-------+--------+--------+
| Algorithm               |   mae |    mse |     r2 |
+=========================+=======+========+========+
| Linear Regression       | 3.514 | 15.246 |  0.046 |
+-------------------------+-------+--------+--------+
| Decision Tree Regressor | 3.997 | 28.001 | -0.752 |
+-------------------------+-------+--------+--------+