# Funksiya rewiev

In [1]:
import pandas as pd

In [29]:
df=pd.read_csv('jobs.csv')

In [30]:
df.head()

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,59,Master's,6.0,Finance,Accountant,Medium,Entry,84.0,21.0,94,Medium,5.0,7.0,40,26,High
1,44,Master's,14.0,Manufacturing,Production Supervisor,Small,Entry,30.0,84.0,68,Low,2.0,2.0,14,9,Low
2,36,Bachelor's,7.0,Retail,Store Manager,Medium,Senior,12.0,86.0,71,Low,0.0,1.0,6,3,Low
3,27,Bachelor's,6.0,Finance,Auditor,Large,Entry,90.0,18.0,21,Medium,3.0,10.0,67,26,High
4,49,High School,12.0,Finance,Auditor,Small,Entry,49.0,52.0,72,Medium,5.0,13.0,26,19,Medium

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  str
 2   Years_of_Experience         19998 non-null  float64
 3   Industry                    20000 non-null  str
 4   Job_Role                    20000 non-null  str
 5   Company_Size                19998 non-null  str
 6   Job_Level                   19994 non-null  str
 7   Routine_Task_Percentage     19995 non-null  float64
 8   Creativity_Requirement      19998 non-null  float64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           19998 non-null  str
 11  Number_of_AI_Tools_Used     19995 non-null  float64
 12  AI_Usage_Hours_Per_Week     19995 non-null  float64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 19998 non-null  str
dtypes: float64(5), int64(4), str(7)
memory usage: 2.4 MB

In [32]:
df.isnull().sum()

Age                           0
Education_Level               0
Years_of_Experience           2
Industry                      0
Job_Role                      0
Company_Size                  2
Job_Level                     6
Routine_Task_Percentage       5
Creativity_Requirement        2
Human_Interaction_Level       0
AI_Adoption_Level             2
Number_of_AI_Tools_Used       5
AI_Usage_Hours_Per_Week       5
Tasks_Automated_Percentage    0
AI_Training_Hours             0
Layoff_Risk                   2
dtype: int64

In [33]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df.fillna({col:df[col].mode()[0]},inplace=True)
            else:
                df.fillna({col:df[col].mean()},inplace=True)
    return df

In [34]:
df=toldir(df)

In [35]:
df.isnull().sum()

Age                           0
Education_Level               0
Years_of_Experience           0
Industry                      0
Job_Role                      0
Company_Size                  0
Job_Level                     0
Routine_Task_Percentage       0
Creativity_Requirement        0
Human_Interaction_Level       0
AI_Adoption_Level             0
Number_of_AI_Tools_Used       0
AI_Usage_Hours_Per_Week       0
Tasks_Automated_Percentage    0
AI_Training_Hours             0
Layoff_Risk                   0
dtype: int64

In [36]:
df.nunique()

Age                            40
Education_Level                 4
Years_of_Experience            28
Industry                        8
Job_Role                       24
Company_Size                    3
Job_Level                       3
Routine_Task_Percentage        86
Creativity_Requirement        102
Human_Interaction_Level        80
AI_Adoption_Level               3
Number_of_AI_Tools_Used        12
AI_Usage_Hours_Per_Week        32
Tasks_Automated_Percentage     90
AI_Training_Hours              80
Layoff_Risk                     3
dtype: int64

In [37]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [38]:
encoder=LabelEncoder()
encoder

LabelEncoder()

In [39]:
def codla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            
                df[col]=encoder.fit_transform(df[col])
    return(df)

In [40]:
codla(df)

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,59,2,6.0,1,1,1,0,84.0,21.0,94,2,5.0,7.0,40,26,0
1,44,2,14.0,5,14,2,0,30.0,84.0,68,1,2.0,2.0,14,9,1
2,36,0,7.0,6,19,1,2,12.0,86.0,71,1,0.0,1.0,6,3,1
3,27,0,6.0,1,2,0,0,90.0,18.0,21,2,3.0,10.0,67,26,0
4,49,1,12.0,1,2,2,0,49.0,52.0,72,2,5.0,13.0,26,19,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,56,0,10.0,6,17,2,0,29.0,62.0,44,1,0.0,4.0,16,0,2
19996,43,0,9.0,5,14,1,0,87.0,20.0,20,0,9.0,23.0,77,67,0
19997,28,1,7.0,7,21,1,0,91.0,2.0,49,2,2.0,14.0,55,10,0
19998,46,0,3.0,5,15,1,2,76.0,40.0,89,2,3.0,13.0,66,5,2
19999,36,0,5.0,6,19,1,1,45.0,65.0,75,1,1.0,0.0,30,8,2

In [41]:
df=codla(df)

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  int64
 2   Years_of_Experience         20000 non-null  float64
 3   Industry                    20000 non-null  int64
 4   Job_Role                    20000 non-null  int64
 5   Company_Size                20000 non-null  int64
 6   Job_Level                   20000 non-null  int64
 7   Routine_Task_Percentage     20000 non-null  float64
 8   Creativity_Requirement      20000 non-null  float64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  int64
 11  Number_of_AI_Tools_Used     20000 non-null  float64
 12  AI_Usage_Hours_Per_Week     20000 non-null  float64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  int64
dtypes: float64(5), int64(11)
memory usage: 2.4 MB

# Algorithm

In [43]:
from sklearn.linear_model import LogisticRegression,LinearRegression

In [44]:
log_reg=LogisticRegression()
log_reg

LogisticRegression()

In [46]:
x=df.drop('Layoff_Risk',axis=1)

In [47]:
x

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours
0,59,2,6.0,1,1,1,0,84.0,21.0,94,2,5.0,7.0,40,26
1,44,2,14.0,5,14,2,0,30.0,84.0,68,1,2.0,2.0,14,9
2,36,0,7.0,6,19,1,2,12.0,86.0,71,1,0.0,1.0,6,3
3,27,0,6.0,1,2,0,0,90.0,18.0,21,2,3.0,10.0,67,26
4,49,1,12.0,1,2,2,0,49.0,52.0,72,2,5.0,13.0,26,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,56,0,10.0,6,17,2,0,29.0,62.0,44,1,0.0,4.0,16,0
19996,43,0,9.0,5,14,1,0,87.0,20.0,20,0,9.0,23.0,77,67
19997,28,1,7.0,7,21,1,0,91.0,2.0,49,2,2.0,14.0,55,10
19998,46,0,3.0,5,15,1,2,76.0,40.0,89,2,3.0,13.0,66,5
19999,36,0,5.0,6,19,1,1,45.0,65.0,75,1,1.0,0.0,30,8

In [48]:
y=df['Layoff_Risk']

# train

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [56]:
x_train.shape

(16000, 15)

In [57]:
log_reg.fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# prediction

In [58]:
y_pred=log_reg.predict(x_test)

In [59]:
y_pred

array([2, 1, 2, ..., 2, 2, 1], shape=(4000,))

# evaluation

In [ ]:
from sklearn.metrics import accuracy_score,classification_report

In [61]:
class_report=classification_report(y_test,y_pred)

In [64]:
print(class_report)

              precision    recall  f1-score   support

           0       0.86      0.89      0.88      1375
           1       0.86      0.88      0.87      1296
           2       0.75      0.71      0.73      1329

    accuracy                           0.83      4000
   macro avg       0.82      0.83      0.82      4000
weighted avg       0.82      0.83      0.83      4000

# Vazifa

In [65]:
from sklearn.metrics import confusion_matrix,classification_report

In [66]:
y_actual=[1,0,0,1,0,1,1,0,1]
y_predict=[1,0,1,0,0,1,0,0,1]
cm=confusion_matrix(y_actual,y_predict)

In [67]:
cm

array([[3, 1],
       [2, 3]])

In [68]:
c_report=classification_report(y_actual,y_predict)

In [69]:
print(c_report)

              precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       0.75      0.60      0.67         5

    accuracy                           0.67         9
   macro avg       0.68      0.68      0.67         9
weighted avg       0.68      0.67      0.67         9