# Funksiya

In [1]:
import pandas as pd

In [11]:
df=pd.read_csv('iphonesales.csv')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Customer_Name   100 non-null    str
 2   Country         98 non-null     str
 3   iPhone_Model    98 non-null     str
 4   Storage         98 non-null     str
 5   Color           100 non-null    str
 6   Quantity        97 non-null     float64
 7   Price           99 non-null     float64
 8   Sale_Date       100 non-null    str
 9   Payment_Method  98 non-null     str
dtypes: float64(2), int64(1), str(7)
memory usage: 7.9 KB

In [13]:
df.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,1004,Customer_4,NaN,iPhone 15 Pro Max,512GB,Black,NaN,1290.0,2025-03-24,Debit Card
4,1005,Customer_5,NaN,iPhone 15,128GB,Blue,NaN,1092.0,2025-02-01,Debit Card

In [14]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
Country           2
iPhone_Model      2
Storage           2
Color             0
Quantity          3
Price             1
Sale_Date         0
Payment_Method    2
dtype: int64

In [22]:
def toldir(df):
        
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df.fillna({col:df[col].mode()[0]},inplace=True)
            else:
                df.fillna({col:df[col].mean()},inplace=True)
                
    return(df)

In [24]:
toldir(df)

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5.000000,1817.0,2025-05-01,Debit Card
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1.000000,998.0,2025-03-05,PayPal
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.000000,876.0,2025-01-25,Credit Card
3,1004,Customer_4,UK,iPhone 15 Pro Max,512GB,Black,3.329897,1290.0,2025-03-24,Debit Card
4,1005,Customer_5,UK,iPhone 15,128GB,Blue,3.329897,1092.0,2025-02-01,Debit Card
...,...,...,...,...,...,...,...,...,...,...
95,1096,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1.000000,1743.0,2025-03-09,Credit Card
96,1097,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3.000000,1671.0,2025-02-08,Credit Card
97,1098,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4.000000,1125.0,2025-01-08,Debit Card
98,1099,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5.000000,1540.0,2025-02-04,Debit Card
99,1100,Customer_100,UK,iPhone 15,512GB,Blue,3.000000,1549.0,2025-03-28,Debit Card

In [25]:

df=toldir(df)
df.isnull().sum()

Order_ID          0
Customer_Name     0
Country           0
iPhone_Model      0
Storage           0
Color             0
Quantity          0
Price             0
Sale_Date         0
Payment_Method    0
dtype: int64